server:
  port: 1026

bootstrap:
  servers: ${KAFKA_BOOTSTRAP}:${KAFKA_PORT}         #edited
  
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

directDbConnection: true 
#if directDbConnection is false then properties below are not used {{{
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS}:${KAFKA_PORT}      #edited
  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVICE}:${POSTGRES_PORT}/ngb?ApplicationName=ngb_querymanager
    username: ngb
    password: ngb
    hikari: 
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      poolName: SpringBootHikariCP
      maxLifetime: 2000000
      connectionTimeout: 30000
#}}}

# Keycloak Server Information
keycloak:
  auth-server-url: ${KEYCLOAK_SERVER_URL}
  credentials:
    secret: ${CLIENT_SECRET}
  realm: ${REALM}
  bearer-only: 'true'
  use-resource-role-mappings: 'true'
  ssl-required: ${SSL_REQUIRED}
  resource: ${CLIENT_ID}