mysettings:
  application-name: query-manager
  kafka:
    bootstrap:
      host: ${bushost:localhost}
      port: ${busport:9092}
  postgres:
    host: ${dbhost:localhost}
    port: ${dbport:5432}
    username: ${dbuser:ngb}
    password: ${dbpass:ngb}
    database-name: ${dbname:ngb}
  gateway:
    host: ${gateway.host:localhost}
    port: ${gateway.port:9090}
jdbcurl: jdbc:postgresql://${mysettings.postgres.host}:${mysettings.postgres.port}/${mysettings.postgres.database-name}?ApplicationName=${mysettings.application-name}
bootstrap:
  servers: ${mysettings.kafka.bootstrap.host}:${mysettings.kafka.bootstrap.port}
spring:
  application.name: ${mysettings.application-name}
  security:
    active: false
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://idp.example.com/auth/realms/demo
#      client:
#        provider:
#          keycloak:
#            issuer-uri: https://idp.example.com/auth/realms/demo
#        registration:
#          keycloak-client:
#            provider: keycloak
#            client-id: spring-security
#            client-secret: 6cea952f-10d0-4d00-ac79-cc865820dc2c
#            authorization_grant_type: client_credentials
#          keycloak:
#            client-id: spring-security
#            client-secret: 6cea952f-10d0-4d00-ac79-cc865820dc2c
  main:
    lazy-initialization: false
  kafka:
    producer:
      bootstrap-servers: ${bootstrap.servers}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: ${bootstrap.servers}
      group-id: ${mysettings.application-name}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        cleanup:
          policy: compact  
  flyway:
    baselineOnMigrate: true
  datasource:
    password: ${mysettings.postgres.password}
    url: ${jdbcurl}
    username: ${mysettings.postgres.username}
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      poolName: SpringBootHikariCP
      maxLifetime: 2000000
      connectionTimeout: 30000

server:
  port: 1026
  tomcat:
    max:
      threads: 50
#Entity-Manager properties
entity:
  topic: ENTITY
  keyValues:
    topic: KVENTITY
  withoutSysAttrs:
    topic: ENTITY_WITHOUT_SYSATTRS
query:
  topic: QUERY
  result:
    topic: QUERY_RESULT
csource:
  query:
    topic: CONTEXT_REGISTRY_QUERY
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    restart:
      enabled: true
      
atcontext:
  url: http://${mysettings.gateway.host}:${mysettings.gateway.port}/ngsi-ld/contextes/
ngb:
  debugmode: false
kafka:
  replytimeout: 10000
  
defaultLimit: 50
maxLimit: 500
directDbConnection: true 
ngsild:
  corecontext: https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.3.jsonld