apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: atctxsrv
  name: atctxsrv
spec:
  replicas: 1
  selector:
    matchLabels:
      service: atctxsrv
  strategy: {}
  template:
    metadata:
      labels:
        service: atctxsrv
    spec:
      containers:
      - image: scorpiobroker/scorpio:AtContextServer_latest
        imagePullPolicy: ""
        name: atctxsrv
        ports:
        - containerPort: 27015
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --silent http://localhost:27015/actuator/health | grep --quiet -e
              '^{\"status\"\:\"UP\".*}$'
          failureThreshold: 10
          initialDelaySeconds: 20
          periodSeconds: 5
        resources:
          limits:
            cpu: 575m
            memory: 2280Mi
          requests:
            cpu: 450m
            memory: 1850Mi
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}

