apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: cfgsrv
  name: cfgsrv
spec:
  replicas: 1
  selector:
    matchLabels:
      service: cfgsrv
  strategy: {}
  template:
    metadata:
      labels:
        service: cfgsrv
    spec:
      containers:
      - image: scorpiobroker/scorpio:config-server_latest
        imagePullPolicy: ""
        name: cfgsrv
        ports:
        - containerPort: 8888
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --silent http://localhost:8888/actuator/health | grep --quiet -e
              '^{\"status\"\:\"UP\".*}$'
          failureThreshold: 10
          initialDelaySeconds: 20
          periodSeconds: 5
        resources:
          limits:
            cpu: 575m
            memory: 2280Mi
          requests:
            cpu: 450m
            memory: 1850Mi
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}

