apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: emgr
  name: emgr
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      service: emgr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: emgr
    spec:
      containers:
      - image: scorpiobroker/scorpio:EntityManager_latest
        imagePullPolicy: IfNotPresent
        name: emgr
        ports:
        - containerPort: 1025
          protocol: TCP
        resources:
          limits:
            cpu: 875m
            memory: 2280Mi
          requests:
            cpu: 850m
            memory: 1850Mi
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
