apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: eureka
  name: eureka
  namespace: scorpio-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      service: eureka
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: eureka
    spec:
      containers:
      - image: ibn40/digitaltwin:eureka-server_test
        imagePullPolicy: Always
        name: eureka
        env:                            #edited
        - name: KAFKA_BROKERS
          value: "my-cluster-kafka-brokers"
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_BOOTSTRAP
          value: "my-cluster-kafka-bootstrap"
        ports:
        - containerPort: 8761
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1280Mi
          requests:
            cpu: 250m
            memory: 600Mi
      restartPolicy: Always
      serviceAccountName: ""
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}