apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: qrymgr
  name: qrymgr
spec:
  replicas: 1
  selector:
    matchLabels:
      service: qrymgr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: qrymgr
    spec:
      containers:
      - image: scorpiobroker/scorpio:QueryManager_latest
        imagePullPolicy: IfNotPresent
        name: qrymgr
        ports:
        - containerPort: 1026
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1280Mi
          requests:
            cpu: 250m
            memory: 600Mi
      restartPolicy: Always
status: {}
