apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: query-manager
  name: query-manager
  namespace: scorpio-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      service: query-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: query-manager
    spec:
      containers:
      - image: :ibn40/digitaltwin:QueryManager_test
        imagePullPolicy: Always
        name: query-manager
        env:                            #edited
        - name: KAFKA_BROKERS
          value: "my-cluster-kafka-brokers"
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_BOOTSTRAP
          value: "my-cluster-kafka-bootstrap"
        ports:
        - containerPort: 1026
          protocol: TCP
        lifecycle:
           preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - curl -X PUT "http://eureka:8761/eureka/apps/QUERY-MANAGER/$HOSTNAME:query-manager:1026/status?value=OUT_OF_SERVICE"
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --silent http://localhost:1026/actuator/health | grep --quiet -e
              '^{\"status\"\:\"UP\".*}$'
          failureThreshold: 10
          initialDelaySeconds: 20
          periodSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 1280Mi
          requests:
            cpu: 250m
            memory: 600Mi
      restartPolicy: Always
      serviceAccountName: ""
status: {}
