apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: storage-manager
  name: storage-manager
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      service: storage-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: storage-manager
    spec:
      containers:
      - image: ibn40/digitaltwin:StorageManager_test
        imagePullPolicy: Always
        name: storage-manager
        env:                            #edited
        - name: KAFKA_BROKERS
          value: "my-cluster-kafka-brokers"
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_BOOTSTRAP
          value: "my-cluster-kafka-bootstrap"
        ports:
        - containerPort: 1029
          protocol: TCP
        lifecycle:
           preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - curl -X PUT "http://eureka:8761/eureka/apps/STORAGE-MANAGER/$HOSTNAME:storage-manager:1029/status?value=OUT_OF_SERVICE"
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --silent http://localhost:1029/actuator/health | grep --quiet -e
              '^{\"status\"\:\"UP\".*}$'
          failureThreshold: 7
          initialDelaySeconds: 25
          periodSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 1280Mi
          requests:
            cpu: 250m
            memory: 600Mi
      restartPolicy: Always
      serviceAccountName: ""
status: {}
