apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: stomgr
    name: stomgr
spec:
  replicas: 1
  selector:
    matchLabels:
      service: stomgr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: stomgr
    spec:
      containers:
      - image: scorpiobroker/scorpio:StorageManager_latest
        imagePullPolicy: IfNotPresent
        name: stomgr
        ports:
        - containerPort: 1029
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1280Mi
          requests:
            cpu: 250m
            memory: 600Mi
      restartPolicy: Always
status: {}
