apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: sbsmgr
  name: sbsmgr
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      service: sbsmgr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: sbsmgr
    spec:
      containers:
      - image: scorpiobroker/scorpio:SubscriptionManager_latest
        imagePullPolicy: IfNotPresent
        name: sbsmgr
        ports:
        - containerPort: 2025
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1280Mi
          requests:
            cpu: 250m
            memory: 600Mi
      restartPolicy: Always
status: {}
