version: '3'
services:
  postgrestwo:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
  scorpiotwo:
    image: scorpiobroker/all-in-one-runner:java-latest
    environment:
      DBHOST: postgrestwo
    ports:
      - "9070:9090"
    depends_on:
      - postgrestwo
