version: '3'

services:
  testserver:
    image: testserver
    ports:
     - "8080:8080"
  zookeeper:
    image: zookeeper
    ports:
      - "2181"
  kafka:
    image: bitnami/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_MS: 10000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  postgres:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
  eureka:
    image: scorpiobroker/scorpio:eureka-server_latest
    ports:
      - "8761"
  gateway:
    image: scorpiobroker/scorpio:gateway_aaio_latest
    ports:
      - "9090:9090"
    depends_on:
      - eureka
  emgr:
    image: scorpiobroker/entity-manager-windows-kafka-eureka-latest
    environment:
      DBHOST: postgres
      BUSHOST: kafka
      QUARKUS_EUREKA_SERVICE-URL_DEFAULT: "http://eureka:8761/eureka"
    ports:
      - "1025"
    depends_on:
      - kafka
      - eureka
  histmgr:
    image: scorpiobroker/history-manager-windows-kafka-eureka-latest
    environment:
      DBHOST: postgres
      BUSHOST: kafka
      QUARKUS_EUREKA_SERVICE-URL_DEFAULT: "http://eureka:8761/eureka"
    ports:
      - "1040"
    depends_on:
      - kafka
      - gateway
      - eureka
  qrymgr:
    image: scorpiobroker/query-manager-windows-kafka-eureka-latest
    environment:
      DBHOST: postgres
      BUSHOST: kafka
      QUARKUS_EUREKA_SERVICE-URL_DEFAULT: "http://eureka:8761/eureka"
    ports:
      - "1026"
    depends_on:
      - kafka
      - postgres
      - eureka
  regmgr:
    image: scorpiobroker/registry-manager-windows-kafka-eureka-latest
    environment:
      DBHOST: postgres
      BUSHOST: kafka
      QUARKUS_EUREKA_SERVICE-URL_DEFAULT: "http://eureka:8761/eureka"
    ports:
      - "1030"
    depends_on:
      - kafka
      - postgres
      - gateway
      - eureka
  regsbsmgr:
    image: scorpiobroker/registry-subscription-manager-windows-kafka-eureka-latest
    environment:
      DBHOST: postgres
      BUSHOST: kafka
      QUARKUS_EUREKA_SERVICE-URL_DEFAULT: "http://eureka:8761/eureka"
    ports:
      - "2025"
    depends_on:
      - kafka
      - postgres
      - eureka
  sbsmgr:
    image: scorpiobroker/subscription-manager-windows-kafka-eureka-latest
    environment:
      DBHOST: postgres
      BUSHOST: kafka
      QUARKUS_EUREKA_SERVICE-URL_DEFAULT: "http://eureka:8761/eureka"
    ports:
      - "2026"
    depends_on:
      - kafka
      - eureka