apiVersion: v1
kind: Service
metadata:
  labels:
    service: regmgr
  name: regmgr
spec:
  ports:
  - name: "1030"
    port: 1030
    targetPort: 1030
  selector:
    service: regmgr
status:
  loadBalancer: {}

