mysettings:
  eureka:
    port: ${eurekaport:8761}
spring:
  application:
    name: eureka-server
  main:
    allow-bean-definition-overriding: true
server:
  port: ${mysettings.eureka.port}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  level:
    root: INFO
