apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: registry-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: regmgr
 minReplicas: 1
 maxReplicas: 5
 targetCPUUtilizationPercentage: 80