apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: zookeeper-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: zookeeper
 minReplicas: 2
 maxReplicas: 5
 targetCPUUtilizationPercentage: 70
