server:
  port: 1029

bootstrap:
  servers: ${KAFKA_BOOTSTRAP}:${KAFKA_PORT}         #edited

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS}:${KAFKA_PORT}      #edited

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

reader:
  enabled: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVICE}:{POSTGRES_PORT}/ngb?ApplicationName=ngb_storagemanager_reader
    username: ngb
    password: ngb
    hikari: 
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      poolName: SpringBootHikariCP
      maxLifetime: 2000000
      connectionTimeout: 30000

writer:
  enabled: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVICE}:{POSTGRES_PORT}/ngb?ApplicationName=ngb_storagemanager_writer
    username: ngb
    password: ngb
    hikari: 
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      poolName: SpringBootHikariCP
      maxLifetime: 2000000
      connectionTimeout: 30000
