mysettings:
  kafka:
    bootstrap:
      port: ${busport:9092}
  eureka:
    protocol: ${eurekaprotocol:http}
    host: ${eureka.host:eureka}
    port: ${eurekaport:8761}
eurekaurl: ${mysettings.eureka.protocol}://${mysettings.eureka.host}:${mysettings.eureka.port}
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eurekaurl}/eureka/