apiVersion: v1
kind: Service
metadata:
  labels:
    service: atctxsrv
  name: atctxsrv
spec:
  ports:
  - name: "27015"
    port: 27015
    targetPort: 27015
  selector:
    service: atctxsrv
status:
  loadBalancer: {}

