apiVersion: v1
kind: Service
metadata:
  labels:
    service: emgr
  name: emgr
spec:
  ports:
  - name: "1025"
    port: 1025
    targetPort: 1025
  selector:
    service: emgr
status:
  loadBalancer: {}

