apiVersion: v1
kind: Service
metadata:
  labels:
    service: qrymgr
  name: qrymgr
spec:
  ports:
  - name: "1026"
    port: 1026
    targetPort: 1026
  selector:
    service: qrymgr
status:
  loadBalancer: {}
