spring:
  application:
    name: testmanager
  kafka:
    admin:
      properties:
        cleanup:
          policy: compact
  cloud:
    stream:
      kafka:
        binder:
     #     brokers:  ${KAFKA_BROKERS}:${KAFKA_PORT}      #edited
      #bindings:
        #ENTITY_READ_CHANNEL:
         # destination: ENTITY
         # contentType: application/json
         # group: entity
server:
  port: 1010
  tomcat:
    max:
      threads: 20
#Entity-Manager properties
entity:
  topic: ENTITY
query:
  topic: QUERY
  result:
    topic: QUERY_RESULT
bootstrap:
  servers: ${KAFKA_BOOTSTRAP}:${KAFKA_PORT}         #edited
#enable log compaction

              
          