mysettings:
  application-name: gateway
  eureka:
    protocol: ${eurekaprotocol:http}
    host: ${eurekahost:localhost}
    port: ${eurekaport:8761}
  gateway:
    port: ${gateway.port:9090}
eurekaurl: ${mysettings.eureka.protocol}://${mysettings.eureka.host}:${mysettings.eureka.port}
# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


#GET request configuration for QUERY-MANAGER 
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
server:
  port: ${mysettings.gateway.port}
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eurekaurl}/eureka/

# Configure the Authorization Server and User Info Resource Server details
security:
  active: false
  oauth2:
    client:
    # for keycloak configure
      #accessTokenuri: no://op
      #userAuthorizationuri: no://op
      #clientId: authserver
      #clientSecret: ae8c99a9-f98d-41e9-8fb2-d348acb987e0
    # for ketrock configure  
      accessTokenuri: no://op
      userAuthorizationuri: no://op
      clientId: a2034c11-d2a9-4cab-9fac-ff65425bd53f
      clientSecret: 7364baec-6d6f-4307-8c71-d66e1e6c3afc
    resource:
    # for keycloak configure
      #userInfouri: no://op
    # for keycloak configure
      userInfouri: no://op
    
spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
      - id: QUERY-MANAGER
        uri: no://op
        predicates:
        - Method=GET
        - Path=/ngsi-ld/v1/entities/**
      - id: ENTITY-MANAGER
        uri: no://op
        predicates:
        - Method=POST,PATCH,DELETE
        - Path=/ngsi-ld/v1/entities/**
      - id: QUERY-MANAGER
        uri: no://op
        predicates:
        - Method=GET
        - Path=/ngsi-ld/v1/attributes/**
      - id: QUERY-MANAGER
        uri: no://op
        predicates:
        - Method=GET
        - Path=/ngsi-ld/v1/types/**
      - id: QUERY-MANAGER
        uri: no://op
        predicates:
        - Method=POST
        - Path=/ngsi-ld/v1/entityOperations/query/**
      - id: ENTITY-MANAGER
        uri: no://op
        predicates:
        - Method=POST
        - Path=/ngsi-ld/v1/entityOperations/**
      - id: SUBSCRIPTION-MANAGER
        uri: no://op
        predicates:
        - Method=GET,POST,PATCH,DELETE
        - Path=/ngsi-ld/v1/subscriptions/**
      - id: C-SOURCES
        uri: no://op
        predicates:
        - Method=GET,POST,PATCH,DELETE
        - Path=/ngsi-ld/v1/csourceRegistrations/**
      - id: C-SOURCES
        uri: no://op
        predicates:
        - Method=GET,POST,PATCH,DELETE
        - Path=/ngsi-ld/v1/csourceSubscriptions/**
      - id: HISTORY-MANAGER
        uri: no://op
        predicates:
        - Method=GET,POST,PATCH,DELETE
        - Path=/ngsi-ld/v1/temporal/entities/**
      - id: ATCONTEXT-SERVER
        uri: no://op
        predicates:
        - Method=GET
        - Path=/ngsi-ld/contextes/**
      - id: STORAGE-MANAGER
        uri: no://op
        predicates:
        - Method=GET
        - Path=/scorpio/v1/info/**
      - id: INFO-SERVER
        uri: no://op
        predicates:
        - Method=GET
        - Path=/health/** 
      - id: INFO-SERVER
        uri: no://op
        predicates:
        - Method=GET
        - Path=/version/**
      - id: testmanager
        uri: no://op
        predicates:
        - Method=GET,POST,PATCH,DELETE
        - Path=/test/**
logging:
  level:
    root: ERROR
