mysettings:
  application-name: gateway
  eureka:
    protocol: ${eurekaprotocol:http}
    host: ${eurekahost:localhost}
    port: ${eurekaport:8761}
  gateway:
    port: ${gateway.port:9090}
eurekaurl: ${mysettings.eureka.protocol}://${mysettings.eureka.host}:${mysettings.eureka.port}
# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


#GET request configuration for QUERY-MANAGER 
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
server:
  port: ${mysettings.gateway.port}
  tomcat:
    relaxed-path-chars: <,>,[,\,],^,`,{,|,}
    relaxed-query-chars: <,>,[,\,],^,`,{,|,}
    max:
      threads:200
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eurekaurl}/eureka/
  instance:
    preferIpAddress: true
spring:
  security:
    active: false
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://idp.example.com/auth/realms/demo
#      client:
#        provider:
#          keycloak:
#            issuer-uri: https://idp.example.com/auth/realms/demo
#        registration:
#          keycloak-client:
#            provider: keycloak
#            client-id: spring-security
#            client-secret: 6cea952f-10d0-4d00-ac79-cc865820dc2c
#            authorization_grant_type: client_credentials
#          keycloak:
#            client-id: spring-security
#            client-secret: 6cea952f-10d0-4d00-ac79-cc865820dc2c
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
      - uri: lb://QUERY-MANAGER
        id: querymanager
        predicates:
        - Method=GET
        - Path=/ngsi-ld/v1/entities/**
      - uri: lb://ENTITY-MANAGER
        id: entitymanager
        predicates:
        - Method=POST,PATCH,DELETE
        - Path=/ngsi-ld/v1/entities/**
      - uri: lb://QUERY-MANAGER
        id: querymanager1
        predicates:
        - Method=GET
        - Path=/ngsi-ld/v1/attributes/**
      - uri: lb://QUERY-MANAGER
        id: querymanager2
        predicates:
        - Method=GET
        - Path=/ngsi-ld/v1/types/**
      - uri: lb://QUERY-MANAGER
        id: querymanager3
        predicates:
        - Method=POST
        - Path=/ngsi-ld/v1/entityOperations/query/**
      - uri: lb://ENTITY-MANAGER
        id: entitymanager1
        predicates:
        - Method=POST
        - Path=/ngsi-ld/v1/entityOperations/**
      - uri: lb://SUBSCRIPTION-MANAGER
        id: subscriptionsmanager1
        predicates:
        - Method=GET,POST,PATCH,DELETE
        - Path=/ngsi-ld/v1/subscriptions/**
      - uri: lb://C-SOURCES
        id: csourcereg
        predicates:
        - Method=GET,POST,PATCH,DELETE
        - Path=/ngsi-ld/v1/csourceRegistrations/**
      - uri: lb://C-SOURCES
        id: csourcesubs
        predicates:
        - Method=GET,POST,PATCH,DELETE
        - Path=/ngsi-ld/v1/csourceSubscriptions/**
      - uri: lb://HISTORY-MANAGER
        id: history
        predicates:
        - Method=GET,POST,PATCH,DELETE
        - Path=/ngsi-ld/v1/temporal/entities/**
      - uri: lb://ATCONTEXT-SERVER
        id: atcontext
        predicates:
        - Method=GET
        - Path=/ngsi-ld/contextes/**
      - uri: lb://STORAGE-MANAGER
        id: info
        predicates:
        - Method=GET
        - Path=/scorpio/v1/info/**
logging:
  level:
    root: INFO
