spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: aio-runner
        uri: no://op
        predicates:
        - Method=GET
        - Path=/ngsi-ld/v1/entities/**
      - id: aio-runner
        uri: no://op
        predicates:
        - Method=POST,PATCH,DELETE
        - Path=/ngsi-ld/v1/entities/**
      - id: aio-runner
        uri: no://op
        predicates:
        - Method=GET
        - Path=/ngsi-ld/v1/attributes/**
      - id: aio-runner
        uri: no://op
        predicates:
        - Method=GET
        - Path=/ngsi-ld/v1/types/**
      - id: aio-runner
        uri: no://op
        predicates:
        - Method=POST
        - Path=/ngsi-ld/v1/entityOperations/query/**
      - id: aio-runner
        uri: no://op
        predicates:
        - Method=POST
        - Path=/ngsi-ld/v1/entityOperations/**
      - id: aio-runner
        uri: no://op
        predicates:
        - Method=GET,POST,PATCH,DELETE
        - Path=/ngsi-ld/v1/subscriptions/**
      - id: aio-runner
        uri: no://op
        predicates:
        - Method=GET,POST,PATCH,DELETE
        - Path=/ngsi-ld/v1/csourceRegistrations/**
      - id: aio-runner
        uri: no://op
        predicates:
        - Method=GET,POST,PATCH,DELETE
        - Path=/ngsi-ld/v1/csourceSubscriptions/**
      - id: aio-runner
        uri: no://op
        predicates:
        - Method=GET,POST,PATCH,DELETE
        - Path=/ngsi-ld/v1/temporal/entities/**
      - id: aio-runner
        uri: no://op
        predicates:
        - Method=GET
        - Path=/ngsi-ld/contextes/**
      - id: aio-runner
        uri: no://op
        predicates:
        - Method=GET
        - Path=/scorpio/v1/info/**
      - id: aio-runner
        uri: no://op
        predicates:
        - Method=GET
        - Path=/health/** 
      - id: aio-runner
        uri: no://op
        predicates:
        - Method=GET
        - Path=/version/**
      - id: aio-runner
        uri: no://op
        predicates:
        - Method=GET,POST,PATCH,DELETE
        - Path=/test/**