mysettings:
  application-name: gateway
  eureka:
    protocol: ${eurekaprotocol:http}
    host: ${eurekahost:localhost}
    port: ${eurekaport:8761}
  gateway:
    port: ${gateway.port:9090}
eurekaurl: ${mysettings.eureka.protocol}://${mysettings.eureka.host}:${mysettings.eureka.port}
# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


#GET request configuration for QUERY-MANAGER 
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
server:
  port: ${mysettings.gateway.port}
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eurekaurl}/eureka/
spring:
  security:
    active: false
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://idp.example.com/auth/realms/demo
#      client:
#        provider:
#          keycloak:
#            issuer-uri: https://idp.example.com/auth/realms/demo
#        registration:
#          keycloak-client:
#            provider: keycloak
#            client-id: spring-security
#            client-secret: 6cea952f-10d0-4d00-ac79-cc865820dc2c
#            authorization_grant_type: client_credentials
#          keycloak:
#            client-id: spring-security
#            client-secret: 6cea952f-10d0-4d00-ac79-cc865820dc2c
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
      - id: QUERY-MANAGER
        uri: no://op
        predicates:
        - Method=GET
        - Path=/ngsi-ld/v1/entities/**
      - id: ENTITY-MANAGER
        uri: no://op
        predicates:
        - Method=POST,PATCH,DELETE
        - Path=/ngsi-ld/v1/entities/**
      - id: QUERY-MANAGER
        uri: no://op
        predicates:
        - Method=GET
        - Path=/ngsi-ld/v1/attributes/**
      - id: QUERY-MANAGER
        uri: no://op
        predicates:
        - Method=GET
        - Path=/ngsi-ld/v1/types/**
      - id: QUERY-MANAGER
        uri: no://op
        predicates:
        - Method=POST
        - Path=/ngsi-ld/v1/entityOperations/query/**
      - id: ENTITY-MANAGER
        uri: no://op
        predicates:
        - Method=POST
        - Path=/ngsi-ld/v1/entityOperations/**
      - id: SUBSCRIPTION-MANAGER
        uri: no://op
        predicates:
        - Method=GET,POST,PATCH,DELETE
        - Path=/ngsi-ld/v1/subscriptions/**
      - id: C-SOURCES
        uri: no://op
        predicates:
        - Method=GET,POST,PATCH,DELETE
        - Path=/ngsi-ld/v1/csourceRegistrations/**
      - id: C-SOURCES
        uri: no://op
        predicates:
        - Method=GET,POST,PATCH,DELETE
        - Path=/ngsi-ld/v1/csourceSubscriptions/**
      - id: HISTORY-MANAGER
        uri: no://op
        predicates:
        - Method=GET,POST,PATCH,DELETE
        - Path=/ngsi-ld/v1/temporal/entities/**
      - id: ATCONTEXT-SERVER
        uri: no://op
        predicates:
        - Method=GET
        - Path=/ngsi-ld/contextes/**
      - id: STORAGE-MANAGER
        uri: no://op
        predicates:
        - Method=GET
        - Path=/scorpio/v1/info/**
      - id: INFO-SERVER
        uri: no://op
        predicates:
        - Method=GET
        - Path=/health/** 
      - id: INFO-SERVER
        uri: no://op
        predicates:
        - Method=GET
        - Path=/version/**
      - id: testmanager
        uri: no://op
        predicates:
        - Method=GET,POST,PATCH,DELETE
        - Path=/test/**
logging:
  level:
    root: INFO
