server:
  port: 27015

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS}:${KAFKA_PORT}

bootstrap:
  servers: ${KAFKA_BOOTSTRAP}:${KAFKA_PORT} 
  
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
