apiVersion: v1
kind: Service
metadata:
  labels:
    service: eureka
  name: eureka
spec:
  ports:
  - name: "8761"
    port: 8761
    targetPort: 8761
  selector:
    service: eureka
status:
  loadBalancer: {}

