{{- if .Values.kafka.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka
  name: kafka
  namespace: {{.Values.namespace}}
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    service: kafka
status:
  loadBalancer: {}
{{- end }}