{{- if .Values.eureka.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
      service: postgres
  name: postgres
  # namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: postgres
  strategy: {}
  template:
    metadata:
      labels:
       service: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: ngb
        - name: POSTGRES_PASSWORD
          value: ngb
        - name: POSTGRES_USER
          value: ngb
        image: mdillon/postgis
        imagePullPolicy: ""
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgredb
      hostname: postgres      # added new 
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
status: {}
{{- end}}