# to block traffic from all other namespaces
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: block-external-namepsace-traffic
#  namespace: test
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}