# namespace role
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
#  namespace: test
  name: testing-services-admin-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs:
      - create
      - get
      - describe
      - delete
      - list
      - update
      - edit
      - watch
      - exec
      - patch