apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: eureka
  name: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      service: eureka
  strategy: {}
  template:
    metadata:
      labels:
        service: eureka
    spec:
      containers:
      - image: scorpiobroker/scorpio:eureka-server_latest
        imagePullPolicy: ""
        name: eureka
        ports:
        - containerPort: 8761
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}

