name: Build

on:
  push:
    branches: [ TCS-development ]
  pull_request:
    branches: [ TCS-development ]

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Java 11
      run: |
        echo Install Java 11
        echo ---------------
        sudo apt update
        sudo apt install default-jre
    - name: Build Scorpio containers
      run: |
        mvn clean package -DskipTests -Pdocker
    - name: Setup tmate session
      if: failure()
      uses: mxschmitt/action-tmate@v3