# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Java ${{ matrix.java }} 
    strategy: 
      matrix:
        java: [11] 
        
    services:
     zookeeper:
      image: zookeeper
      ports:
      - 2181:2181
     kafka:
       image: wurstmeister/kafka
       ports:
        - 9092:9092
       env:
        KAFKA_ADVERTISED_HOST_NAME: kafka
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_PORT: 9092
        KAFKA_LOG_RETENTION_MS: 10000
        KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
       volumes:
        - /var/run/docker.sock:/var/run/docker.sock
     postgres:
        image: mdillon/postgis
        ports:
        - 5432:5432
        env:
          POSTGRES_USER: ngb
          POSTGRES_PASSWORD: ngb
          POSTGRES_DB: ngb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:    
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }} 
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - uses: actions/checkout@v2   
      - name: Setting Up Environment
        run: |       
         sudo apt update
         sudo apt install nodejs
         sudo apt install npm
         mkdir testsuite
         cd testsuite
         curl -LO https://github.com/ScorpioBroker/NGSI-LD_TestSuite/archive/master.zip
         shasum -a 256 master.zip
         unzip -q master.zip
         rm master.zip
         cd NGSI-LD_TestSuite-master
         npm install
         cd ../..
      - name: Building Scorpio Components
        run: |
         mvn clean package -DskipTests -DskipDefault -PbuildForTest -B
         java -jar ./SpringCloudModules/eureka/target/eureka-server.jar > /dev/null 2>&1 &
         sleep 10
         java -Dspring.profiles.active=aio -jar ./SpringCloudModules/gateway/target/gateway.jar > /dev/null 2>&1 &
         sleep 10
         java -Dspring.profiles.active=dev -jar ./AllInOneRunner/target/AllInOneRunner.jar &
         sleep 80
         while [ `curl -s -o /dev/null -w "%{http_code}" http://localhost:9090/scorpio/v1/info/` -eq 500 ]; do sleep 10; done
      - name: Running Test Cases
        run: | 
         cd testsuite
         cd NGSI-LD_TestSuite-master
         export TEST_ENDPOINT="http://localhost:9090"
         export ACC_ENDPOINT="http://localhost:4444"
         export NOTIFY_ENDPOINT="http://localhost:4444/acc"
         export WEB_APP_PORT=4444
         node accumulator/accumulator.js &
         npm test
         curl http://localhost:9090/scorpio/v1/info/

