# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    services:
      postgres:
        image: postgis/postgis:10-2.5
        env:
          POSTGRES_USER: ngb
          POSTGRES_PASSWORD: ngb
          POSTGRES_DB: ngb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:    
    - name: Setting Up Environment
      run: |        
       mkdir kafka
       cd kafka
       wget https://archive.apache.org/dist/kafka/2.2.0/kafka_2.12-2.2.0.tgz
       tar -xzf kafka_2.12-2.2.0.tgz
       kafka_2.12-2.2.0/bin/zookeeper-server-start.sh kafka_2.12-2.2.0/config/zookeeper.properties > /dev/null 2>&1 &
       sleep 2
       kafka_2.12-2.2.0/bin/kafka-server-start.sh kafka_2.12-2.2.0/config/server.properties > /dev/null 2>&1 &
       sleep 2
       cd ..
