# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:    
    - name: Setting Up Environment
      run: |
        sudo apt-get update
        sudo apt-get install openjdk-11-jdk
        wget https://archive.apache.org/dist/kafka/2.2.0/kafka_2.12-2.2.0.tgz
        tar -xzf kafka_2.12-2.2.0.tgz
        kafka_2.12-2.2.0/bin/zookeeper-server-start.sh kafka_2.12-2.2.0/config/zookeeper.properties > /dev/null 2>&1 &
        kafka_2.12-2.2.0/bin/kafka-server-start.sh kafka_2.12-2.2.0/config/server.properties > /dev/null 2>&1 &
        sudo apt-get install postgresql-10
        service postgresql status
        psql -U postgres -c "create database ngb;"
        psql -U postgres -c "create user ngb with password 'ngb';"
        psql -U postgres -c "alter database ngb owner to ngb;"
        psql -U postgres -c "grant all privileges on database ngb to ngb;"
        psql -U postgres -c "alter role ngb superuser;"
        sudo apt install postgresql-10-postgis-2.4
        sudo apt install postgresql-10-postgis-scripts
        sudo -u postgres psql -U postgres -c "create extension postgis;
