# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:    
    - name: Setting Up Environment
      run: |        
        sudo apt-get update
        sudo apt-get install postgresql-10
        sudo pg_ctlcluster 10 main start
        sudo psql -U postgres -c "create extension postgis;"
        sudo psql -U postgres -c "create database ngb;"
        sudo psql -U postgres -c "create user ngb with password 'ngb';"
        sudo psql -U postgres -c "alter database ngb owner to ngb;"
        sudo psql -U postgres -c "grant all privileges on database ngb to ngb;"
        sudo psql -U postgres -c "alter role ngb superuser;"
