name: Release Java version
on: 
  push:
    branches: "quarkus-release/**"
jobs:
  build-java-aaio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2     
      - name: Set up JDK 1.17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Build testserver
        run: |
          cd testserver
          docker build -t testserver .
      - name: Get release number
        id: get-id
        run: |
          id=$(echo ${{github.ref_name}} | cut -d/ -f2)
          echo "::set-output name=id::$id"
      - name: build-java
        run: |
          rm ./BrokerParent/pom.xml
          mv ./BrokerParent/build-pom.xml ./BrokerParent/pom.xml
          mvn clean package -Din-memory -Pin-memory -Ddocker -Ddocker-tag=java-${{steps.get-id.outputs.id}} -Dos=java -Dquarkus.profile=in-memory
      - name: docker tag
        run: |
          docker tag scorpiobroker/all-in-one-runner:java-${{steps.get-id.outputs.id}} scorpiobroker/all-in-one-runner:java-latest
      - name: start docker aaio 
        run: |
          docker-compose -f ./compose-files/docker-compose-java-aaio-test.yml up &
          sleep 120
      - name: newman action
        uses: matt-ball/newman-action@master
        with:
          collection: api-test.json
          environment: api-test-environment.json
      - name: Stopping Scorpio 
        run: docker-compose -f ./compose-files/docker-compose-java-aaio-test.yml down 
      - name: docker-login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: docker push
        run: |
          docker push scorpiobroker/all-in-one-runner:java-${{steps.get-id.outputs.id}}
          docker push scorpiobroker/all-in-one-runner:java-latest
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SUPER_SECRET }}/
        with:
          tag_name: java-${{steps.get-id.outputs.id}}
          release_name: java-${{steps.get-id.outputs.id}}
          draft: false
          prerelease: false
          body_path: RELEASENOTES
      - name: Zip aaio release
        uses: montudor/action-zip@v1
        with:
            args: zip -qq -r all-in-one-runner.zip AllInOneRunner/target/quarkus-app
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SUPER_SECRET }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./all-in-one-runner.zip
          asset_name: all-in-one-runner.zip
          asset_content_type: application/zip
