name: testing stuff on github
on: [push,pull_request]
jobs:
  build-windows-kafka-eureka:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2     
      - name: Get release number
        id: get-id
        shell: pwsh
        run: |
          ls c:\users\installer\AppData\Roaming
