name: Release Java version
on: 
  push:
    branches: "testing/**"
jobs:
  build-java-kafka:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2     
      - name: Set up JDK 1.17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ECR_ID }}
          aws-secret-access-key: ${{ secrets.ECR_TOKEN }}
          aws-region: eu-central-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Build testserver
        run: |
          cd testserver
          docker build -t testserver .
      - name: Get release number
        id: get-id
        run: |
          id=$(echo ${{github.ref_name}} | cut -d/ -f2)
          echo "::set-output name=id::$id"
      - name: build-java-with-kafka
        run: |
          rm ./BrokerParent/pom.xml
          mv ./BrokerParent/build-pom.xml ./BrokerParent/pom.xml
          mvn clean package -DskipTests -Dkafka -Pkafka -Ddocker -Ddocker-tag=java-kafka-${{steps.get-id.outputs.id}} -Dos=java -Dquarkus.profile=kafka
      - name: docker tag 
        run: |
          docker tag scorpiobroker/at-context-server:java-kafka-${{steps.get-id.outputs.id}} scorpiobroker/at-context-server:java-kafka-latest
          docker tag scorpiobroker/history-entity-manager:java-kafka-${{steps.get-id.outputs.id}} scorpiobroker/history-entity-manager:java-kafka-latest
          docker tag scorpiobroker/history-query-manager:java-kafka-${{steps.get-id.outputs.id}} scorpiobroker/history-query-manager:java-kafka-latest
          docker tag scorpiobroker/registry-subscription-manager:java-kafka-${{steps.get-id.outputs.id}} scorpiobroker/registry-subscription-manager:java-kafka-latest
          docker tag scorpiobroker/registry-manager:java-kafka-${{steps.get-id.outputs.id}} scorpiobroker/registry-manager:java-kafka-latest
          docker tag scorpiobroker/subscription-manager:java-kafka-${{steps.get-id.outputs.id}} scorpiobroker/subscription-manager:java-kafka-latest
          docker tag scorpiobroker/query-manager:java-kafka-${{steps.get-id.outputs.id}} scorpiobroker/query-manager:java-kafka-latest
          docker tag scorpiobroker/entity-manager:java-kafka-${{steps.get-id.outputs.id}} scorpiobroker/entity-manager:java-kafka-latest
          docker tag scorpiobroker/all-in-one-runner:java-kafka-${{steps.get-id.outputs.id}} scorpiobroker/all-in-one-runner:java-kafka-latest
          docker tag scorpiobroker/at-context-server:java-kafka-${{steps.get-id.outputs.id}} public.ecr.aws/scorpiobroker/at-context-server:java-kafka-latest
          docker tag scorpiobroker/history-entity-manager:java-kafka-${{steps.get-id.outputs.id}} public.ecr.aws/scorpiobroker/history-entity-manager:java-kafka-latest
          docker tag scorpiobroker/history-query-manager:java-kafka-${{steps.get-id.outputs.id}} public.ecr.aws/scorpiobroker/history-query-manager:java-kafka-latest
          docker tag scorpiobroker/registry-subscription-manager:java-kafka-${{steps.get-id.outputs.id}} public.ecr.aws/scorpiobroker/registry-subscription-manager:java-kafka-latest
          docker tag scorpiobroker/registry-manager:java-kafka-${{steps.get-id.outputs.id}} public.ecr.aws/scorpiobroker/registry-manager:java-kafka-latest
          docker tag scorpiobroker/subscription-manager:java-kafka-${{steps.get-id.outputs.id}} public.ecr.aws/scorpiobroker/subscription-manager:java-kafka-latest
          docker tag scorpiobroker/query-manager:java-kafka-${{steps.get-id.outputs.id}} public.ecr.aws/scorpiobroker/query-manager:java-kafka-latest
          docker tag scorpiobroker/entity-manager:java-kafka-${{steps.get-id.outputs.id}} public.ecr.aws/scorpiobroker/entity-manager:java-kafka-latest
          docker tag scorpiobroker/all-in-one-runner:java-kafka-${{steps.get-id.outputs.id}} public.ecr.aws/scorpiobroker/all-in-one-runner:java-kafka-latest
          docker tag scorpiobroker/at-context-server:java-kafka-${{steps.get-id.outputs.id}} public.ecr.aws/scorpiobroker/at-context-server:java-kafka-${{steps.get-id.outputs.id}}
          docker tag scorpiobroker/history-entity-manager:java-kafka-${{steps.get-id.outputs.id}} public.ecr.aws/scorpiobroker/history-entity-manager:java-kafka-${{steps.get-id.outputs.id}}
          docker tag scorpiobroker/history-query-manager:java-kafka-${{steps.get-id.outputs.id}} public.ecr.aws/scorpiobroker/history-query-manager:java-kafka-${{steps.get-id.outputs.id}}
          docker tag scorpiobroker/registry-subscription-manager:java-kafka-${{steps.get-id.outputs.id}} public.ecr.aws/scorpiobroker/registry-subscription-manager:java-kafka-${{steps.get-id.outputs.id}}
          docker tag scorpiobroker/registry-manager:java-kafka-${{steps.get-id.outputs.id}} public.ecr.aws/scorpiobroker/registry-manager:java-kafka-${{steps.get-id.outputs.id}}
          docker tag scorpiobroker/subscription-manager:java-kafka-${{steps.get-id.outputs.id}} public.ecr.aws/scorpiobroker/subscription-manager:java-kafka-${{steps.get-id.outputs.id}}
          docker tag scorpiobroker/query-manager:java-kafka-${{steps.get-id.outputs.id}} public.ecr.aws/scorpiobroker/query-manager:java-kafka-${{steps.get-id.outputs.id}}
          docker tag scorpiobroker/entity-manager:java-kafka-${{steps.get-id.outputs.id}} public.ecr.aws/scorpiobroker/entity-manager:java-kafka-${{steps.get-id.outputs.id}}
          docker tag scorpiobroker/all-in-one-runner:java-kafka-${{steps.get-id.outputs.id}} public.ecr.aws/scorpiobroker/all-in-one-runner:java-kafka-${{steps.get-id.outputs.id}}
      - name: start docker aaio 
        run: |
          docker-compose -f ./compose-files/docker-compose-java-aaio-kafka-test.yml up &
          sleep 120
      - name: newman action
        uses: matt-ball/newman-action@master
        with:
          collection: api-test.json
          environment: api-test-aaio-environment.json
      - name: Stopping Scorpio 
        run: docker-compose -f ./compose-files/docker-compose-java-aaio-kafka-test.yml down
#      - name: start docker dist 
#        run: |
#          docker-compose -f ./compose-files/docker-compose-java-dist-kafka-test.yml up &
#          sleep 120
#      - name: newman action
#        uses: matt-ball/newman-action@master
#        with:
#          collection: api-test.json
#          environment: api-test-dist-environment.json
#      - name: Stopping Scorpio 
#        run: docker-compose -f ./compose-files/docker-compose-java-dist-kafka-test.yml down
      - name: docker-login
        uses: docker/login-action@v2
        with:
          username: ${{ steps.login-ecr.outputs.docker_username_public_ecr_aws }}
          password: ${{ steps.login-ecr.outputs.docker_password_public_ecr_aws }}
      - name: docker tag and push
        run: |
          docker push public.ecr.aws/scorpiobroker/at-context-server:java-kafka-${{steps.get-id.outputs.id}}
          docker push public.ecr.aws/scorpiobroker/history-entity-manager:java-kafka-${{steps.get-id.outputs.id}}
          docker push public.ecr.aws/scorpiobroker/history-query-manager:java-kafka-${{steps.get-id.outputs.id}}
          docker push public.ecr.aws/scorpiobroker/registry-subscription-manager:java-kafka-${{steps.get-id.outputs.id}}
          docker push public.ecr.aws/scorpiobroker/registry-manager:java-kafka-${{steps.get-id.outputs.id}}
          docker push public.ecr.aws/scorpiobroker/subscription-manager:java-kafka-${{steps.get-id.outputs.id}}
          docker push public.ecr.aws/scorpiobroker/query-manager:java-kafka-${{steps.get-id.outputs.id}}
          docker push public.ecr.aws/scorpiobroker/entity-manager:java-kafka-${{steps.get-id.outputs.id}}
          docker push public.ecr.aws/scorpiobroker/all-in-one-runner:java-kafka-${{steps.get-id.outputs.id}}
          docker push public.ecr.aws/scorpiobroker/registry-subscription-manager:java-kafka-latest
          docker push public.ecr.aws/scorpiobroker/registry-manager:java-kafka-latest
          docker push public.ecr.aws/scorpiobroker/subscription-manager:java-kafka-latest
          docker push public.ecr.aws/scorpiobroker/query-manager:java-kafka-latest
          docker push public.ecr.aws/scorpiobroker/entity-manager:java-kafka-latest
          docker push public.ecr.aws/scorpiobroker/all-in-one-runner:java-kafka-latest
  build-java-aaio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2     
      - name: Set up JDK 1.17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Build testserver
        run: |
          cd testserver
          docker build -t testserver .
      - name: Get release number
        id: get-id
        run: |
          id=$(echo ${{github.ref_name}} | cut -d/ -f2)
          echo "::set-output name=id::$id"
      - name: build-java
        run: |
          rm ./BrokerParent/pom.xml
          mv ./BrokerParent/build-pom.xml ./BrokerParent/pom.xml
          mvn clean package -DskipTests -Din-memory -Pin-memory -Ddocker -Ddocker-tag=java-${{steps.get-id.outputs.id}} -Dos=java -Dquarkus.profile=in-memory
      - name: docker tag
        run: |
          docker tag scorpiobroker/all-in-one-runner:java-${{steps.get-id.outputs.id}} scorpiobroker/all-in-one-runner:java-latest
      - name: start docker aaio 
        run: |
          docker-compose -f ./compose-files/docker-compose-java-aaio-test.yml up &
          sleep 120
      - name: newman action
        uses: matt-ball/newman-action@master
        with:
          collection: api-test.json
          environment: api-test-aaio-environment.json
      - name: Stopping Scorpio 
        run: docker-compose -f ./compose-files/docker-compose-java-aaio-test.yml down 
      - name: docker-login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
#      - name: docker push
#        run: |
#          docker push scorpiobroker/all-in-one-runner:java-${{steps.get-id.outputs.id}}
#          docker push scorpiobroker/all-in-one-runner:java-latest
