name: testing stuff on github
on: [push,pull_request]
jobs:
  build-windows-kafka-eureka:
    runs-on: windows-latest
    steps:
      - name: Get release number
        shell: pwsh
        run: |
          docker info